/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizz;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author AAKASH
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 900));
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(147, 91, 449, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(147, 142, 449, 22);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(147, 196, 449, 22);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(147, 250, 449, 22);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(147, 297, 449, 22);

        jButton1.setText("Add Question");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(191, 391, 109, 25);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(147, 331, 449, 22);

        jLabel1.setText("Question");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 94, 50, 16);

        jLabel2.setText("Option 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 145, 48, 16);

        jLabel3.setText("Option2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 199, 44, 16);

        jLabel4.setText("Option3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 253, 44, 16);

        jLabel5.setText("Option4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 302, 44, 16);

        jLabel6.setText("Correct Answer");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(41, 334, 89, 16);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(367, 391, 59, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Add New Questions");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 13, 164, 42);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\AAKASH\\Desktop\\rsz_background_image1.png")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1000, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String q=jTextField1.getText();
       String o1=jTextField2.getText();
       String o2=jTextField3.getText();
       String o3=jTextField4.getText();
       String o4=jTextField5.getText();
       String o5=jTextField6.getText();
if(q.isEmpty())
        {
System.out.println();
JOptionPane.showMessageDialog( this, "enter values" );
}
else if(o1.isEmpty())
        {
System.out.println();
JOptionPane.showMessageDialog( this, "enter values" );
}
else if(o2.isEmpty())
        {
System.out.println();
JOptionPane.showMessageDialog( this, "enter values" );
}
else if(o3.isEmpty())
        {
System.out.println();
JOptionPane.showMessageDialog( this, "enter values" );
}
else if(o4.isEmpty())
        {
System.out.println();
JOptionPane.showMessageDialog( this, "enter values" );
}
else if(o5.isEmpty())
        {
System.out.println();
JOptionPane.showMessageDialog( this, "enter values" );
}
else{
  try {
            
Class.forName("com.mysql.jdbc.Driver");
Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz","root","root");

Statement stmt=(Statement) con.createStatement();
stmt.executeUpdate("insert into java (question,opt1,opt2,opt3,opt4,answer) values('"+q+"','"+o1+"','"+o2+"','"+o3+"','"+o4+"','"+o5+"')");
  
  JOptionPane.showMessageDialog( this, "Sucess" );
  }
       
       catch (Exception e){
JOptionPane.showMessageDialog(this, e.getMessage());
}
 
  jTextField1.setText("");
jTextField2.setText("");        
jTextField3.setText("");        
jTextField4.setText("");
jTextField5.setText("");
jTextField6.setText("");
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new login().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
