/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizz;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author AAKASH
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel3.setText("jLabel3");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 900));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Question?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 290, 670, 29);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("Option 1");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(280, 345, 660, 30);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("Option 2");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(280, 380, 660, 30);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setText("Option 3");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(280, 420, 660, 25);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton4.setText("Option 4");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(280, 450, 660, 25);

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 640, 59, 25);

        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 490, 63, 25);

        jButton3.setText("CHECK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(480, 490, 71, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Lets Play the Quiz");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 50, 700, 30);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(470, 550, 420, 50);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 550, 166, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\AAKASH\\Desktop\\rsz_vintage-stylized-solid-elements-flat-animation-on-blue-background-for-the-titles_vnw3hqwlg__f0000.png")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 980, 910);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jLabel6.setText("");
jLabel7.setText("");
        buttonGroup1.clearSelection();
        
       
        jLabel2.setText("");
        int a=1;
 Random random = new Random();
        int number = 0;
        for(int counter=1; counter<=1;counter++){
        number = 1+random.nextInt(10);
        System.out.println(number);
        jTextField1.setText(""+number);
        }    

        try {
            
Class.forName("com.mysql.jdbc.Driver");
Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz","root","root");

Statement stmt=(Statement) con.createStatement();
ResultSet rs = stmt.executeQuery("select * from java where id = "+number+"");

       while(rs.next())
{
                jLabel3.setText(rs.getString("id"));
                jLabel1.setText(rs.getString("question"));
                jRadioButton1.setText(rs.getString("opt1"));
                jRadioButton2.setText(rs.getString("opt2"));
                jRadioButton3.setText(rs.getString("opt3"));
                jRadioButton4.setText(rs.getString("opt4"));

            }}
        
//Username is the coloumn name in the database table 
catch (Exception e){
JOptionPane.showMessageDialog(this, e.getMessage());
}
    
        
       
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//int a=1;
 //Random random = new Random();
   //     int number = 0;
     //   for(int counter=1; counter<=1;counter++){
       // number = 1+random.nextInt(2);
        //System.out.println(number);
        //jTextField1.setText(""+number);
        //}    
int number = Integer.parseInt(jTextField1.getText()) ;
        try {
            
Class.forName("com.mysql.jdbc.Driver");
Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz","root","root");
/*As we are creating a connection on a local computer we will write the url as jdbc:mysql://localhost:3306 */
Statement stmt=(Statement) con.createStatement();
ResultSet rs = stmt.executeQuery("select * from java where id = "+number+"");
//String sql = "select * from java where id=?";


        //p = connect.prepareStatement(rs);
       //p.setString(1,jTextField1.getText());
        // rs = p.executeQuery();
        
while(rs.next())
{
if(jRadioButton1.isSelected()) 
        //gender="Male";
    //System.out.print("male"+jRadioButton1.getText());
 jLabel4.setText(""+jRadioButton1.getText());
else if(jRadioButton2.isSelected()) 
jLabel4.setText(""+jRadioButton2.getText()); 
//System.out.print("femal");
else if(jRadioButton3.isSelected())
jLabel4.setText(""+jRadioButton3.getText());
//    System.out.print("3");
else if(jRadioButton4.isSelected())
jLabel4.setText(""+jRadioButton4.getText());
//    System.out.print("4");
else
{    jLabel4.setText("nothing");
 jLabel6.setText("First Choose some Option");
}   
                
                System.out.print(rs.getString("answer"));
                jLabel5.setText(rs.getString("answer"));
                
                String a=jLabel4.getText();
                String b=jLabel5.getText();
                
                if(a.equals(b)){
System.out.println("yes");
jLabel7.setText(rs.getString("answer"));
jLabel6.setText("Correct! Your answer is right:-");                }
                else{
                    System.out.println("no");
                    jLabel7.setText(rs.getString("answer"));
jLabel6.setText("The Correct  Answer is:-");
                }//if (a==b){
                //System.out.print("yes");
                //}
                //else{
                //System.out.print("no");
                //}
               // String b
//jRadioButton1.getActionCommand();
}}
        
//Username is the coloumn name in the database table 
catch (Exception e){
JOptionPane.showMessageDialog(this, e.getMessage());
}
    
        
            // TODO add your handling code here:
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new NewJFrame2().setVisible(true);

        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
